services:
  webhooks_test_app:
    #image: ttl.sh/c18c6432-80d4-45ce-8689-cee8a99f2a37-04:2h
    #image: ghcr.io/hm
    #image: unknown_nginx
    image: uffizzitest/test-private-repo
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

x-uffizzi-ingress:
  service: webhooks_test_app
  port: 80

x-uffizzi-continuous-preview:
  delete_preview_after: 1h
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
