services:
  nginx:
    image: zipofar/my_nginx_simple:latest
    healthcheck:
      test:
        - CMD
        - ls
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 5
    volumes:
      - /var/db

x-uffizzi:
  ingress:
    service: nginx
    port: 80

x-uffizzi-continuous-preview:
  delete_preview_after: 1h
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
