services:
  redis:
    image: redis:latest

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TEST: test1

  nginx:
    image: nginx


  worker:
    build:
      context: https://github.com/NealArw/example-voting-worker#main
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 250M

  vote:
    build:
      context: https://github.com/NealArw/example-voting-vote#main
      dockerfile: Dockerfile

  result:
    build:
      context: https://github.com/NealArw/example-voting-result#main
      dockerfile: Dockerfile
      
configs:
  my_config:
    file: ./configs/vote.conf
  my_config_2:
    file: ./config2/vote2.conf


continuous_preview:
  deploy_preview_when_pull_request_is_opened: true
  delete_preview_when_pull_request_is_closed: true
  share_to_github: true

ingress:
  service: nginx
  port: 8080
