services:
  bad_redis:
    build:
      context: https://github.com/zipofar/hello-world-1#compose-test
      dockerfile: Dockerfile_bad_redis

  app:
    image: nginx

x-uffizzi:
  ingress:
    service: app
    port: 80
