services:
  hello-world:
    build:
      context: https://github.com/zipofar/hello-world-1#compose-test

x-uffizzi:
  ingress:
    service: hello-world
    port: 80
    
x-uffizzi-continuous-preview:
  share_to_github: true
  delete_preview_after: 1h
  delete_preview_when_pull_request_is_closed: true
  deploy_preview_when_pull_request_is_opened: true
