services:
  redis:
    image: redis:latest

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: ${VOTE_APP_POSTGRES.USER}
      POSTGRES_PASSWORD: ${VOTE_APP_POSTGRES.PASSWORD}

  nginx:
    image: nginx:latest
    configs:
      - source: vote.conf
        target: /etc/nginx/conf.d

  worker:
    image: uffizziqa.azurecr.io/example-worker:latest
    deploy:
      resources:
        limits:
          memory: 250M

  vote:
    image: uffizziqa.azurecr.io/example-vote:latest

  result:
    image: uffizziqa.azurecr.io/example-result:latest

ingress:
  service: nginx
  port: 8080
