services:
  hello-world:
    build:
      context: https://github.com/7R41N33/hello-world:master
    environment:
      MULTILINE_KEY: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEowIBAAKCAQEAvt9uoL0Ke7He/EmdxhfBn3hwg0WLASk6zoxLlTcvNpCMUEED
        QkUUQX9S1PCUDuW8Urr87ZRCnzurnj7EGjFSeKS7qt4kesIfaAsyBC8Sf8D7IZ7d
        QuOS/f1R5Qt1ofSSmgmUvg6rROJs7CqtI0YLYysr2Dn2fuTZf4Jc
        -----END RSA PRIVATE KEY-----
      SECRET: 'secret'
      RAILS_WORKERS_COUNT: 0
      RAILS_ENV: ${HW_TEST.RAILS_ENV}
      APP_URL: 'http://lvh.me:7000'
      APP_LOGIN: ${HW_TEST.NAME}
      APP_PASSWORD: ''
      SIDEKIQ_LOGIN: ''
      SIDEKIQ_PASSWORD: ''
      RUBYOPT: -W:no-deprecated -W:no-experimental
      CDN_HOST: https://cdn.cloud?k=1

ingress:
  service: hello-world
  port: 80
