services:
  hello-world:
    build:
      context: .

  redis:
    image: redis

  # db:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: airflow

x-uffizzi:
  ingress:
    service: hello-world
    port: 80
